name: Caption on Image Upload

on:
  push:
    branches:
      - master
  workflow_dispatch:  
  pull_request:
    paths:
      - 'input/**'

permissions:
  contents: write  # Needed to push commits with GITHUB_TOKEN

jobs:
  caption:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run captioning pipeline
        run: |
          python detect_and_caption.py

      - name: Commit and Push Captions
        if: success()  # only run if captioning succeeded
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add output/captions.json || echo "Nothing to add"
          git diff --cached --quiet || git commit -m "Add updated captions"
          git push

      - name: Run unit test
        run: |
          python test_pipeline.py
